apiVersion: apps/v1
kind: Deployment
metadata:
  name: product1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product1
  template:
    metadata:
      labels:
        app: product1
    spec:
      containers:
      - name: product1
        image: gcr.io/oceanic-craft-302516/product1:latest
        ports:
        - containerPort: 8090
        imagePullPolicy: Always